# Generated by Django 5.1.1 on 2024-09-04 21:49

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='The vector to resume', null=True)),
                ('updated_ts', models.DateTimeField(auto_now_add=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('summarry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public.resume',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='resume_vector_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
