# Generated by Django 5.1.1 on 2024-09-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='resume',
        ),
    ]
