# Generated by Django 5.1.1 on 2024-09-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_rename_summarry_resume_summary_alter_resume_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.CharField(),
        ),
    ]
